'use server'

import { createClient } from '@/lib/supabase/server'
import { TABLES } from '@/lib/tables'
import { tenant } from '@/config/tenant'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'

/**
 * Creates a new buin_report (anonymous-friendly).
 * The code BUIN-YYMMDD-XXXXXX is auto-generated by a DB trigger.
 * Evidence is uploaded to buin_evidence/<report_uuid>/<filename>.
 */
export async function createReport(formData: FormData) {
    const supabase = await createClient()

    // Identify user if logged in (optional)
    const { data: { user } } = await supabase.auth.getUser()

    // Parse fields
    const category_id = formData.get('category_id') as string | null
    const description = formData.get('description') as string
    const lat_raw = formData.get('lat')
    const lng_raw = formData.get('lng')
    const address_text = formData.get('address_text') as string | null
    const contact_name = formData.get('contact_name') as string | null
    const contact_phone = formData.get('contact_phone') as string | null
    const contact_email = formData.get('contact_email') as string | null

    const lat = lat_raw ? parseFloat(lat_raw as string) : null
    const lng = lng_raw ? parseFloat(lng_raw as string) : null

    // 1. Validation before calling DB
    if (!description || description.trim().length < 10) {
        return { error: 'La descripción debe tener al menos 10 caracteres.' }
    }
    if (lat === null || lng === null) {
        return { error: 'La ubicación es obligatoria. Por favor marca un punto en el mapa.' }
    }

    // 2. Minimal Payload (ONLY allowed fields for anonymous insert)
    const insertPayload = {
        category_id: category_id || null,
        description: description.trim(),
        lat,
        lng,
        address_text: address_text?.trim() || null,
        // created_by removed to avoid RLS "new row violates policy" for anonymous users
    }

    // 3. Debug logging (Development only)
    if (process.env.NODE_ENV === 'development') {
        console.log('[createReport] Calling RPC create_buin_report with params:', {
            p_category_id: category_id,
            p_description: description.trim(),
            p_lat: lat,
            p_lng: lng,
            p_address_text: address_text?.trim() || null
        })
    }

    // Call secure RPC to bypass RLS for insertion and retrieval
    const { data: rpcData, error: rpcError } = await supabase.rpc('create_buin_report', {
        p_category_id: category_id || null,
        p_description: description.trim(),
        p_lat: lat,
        p_lng: lng,
        p_address_text: address_text?.trim() || null,
        p_contact_name: null,
        p_contact_phone: null,
        p_contact_email: null
    })

    // Robust extraction: RPC with RETURNS TABLE usually returns an array of rows
    const reportRow = Array.isArray(rpcData) ? rpcData[0] : rpcData

    if (process.env.NODE_ENV === 'development') {
        console.log('[createReport] RPC returned:', reportRow)
    }

    if (rpcError || !reportRow || !reportRow.code || !reportRow.private_token) {
        console.error('[createReport] RPC error or missing data:', {
            error: rpcError,
            returnedRow: reportRow
        })
        return { error: `Error guardando reporte (RPC): ${rpcError?.message || 'No se recibieron los tokens de seguimiento'}` }
    }

    // Final redirection using values return by DB
    const finalCode = reportRow.code
    const finalToken = reportRow.private_token
    const reportId = reportRow.id

    if (process.env.NODE_ENV === 'development') {
        console.log('[createReport] Redirecting to voucher with:', { code: finalCode, t: finalToken })
    }

    // Upload evidence file if present
    const evidenceFile = formData.get('evidence') as File | null
    if (evidenceFile && evidenceFile.size > 0 && evidenceFile.name !== 'undefined') {
        // Validate size (max 8MB as requested)
        const MAX_SIZE = 8 * 1024 * 1024
        if (evidenceFile.size > MAX_SIZE) {
            return { error: 'La foto es demasiado pesada (máximo 8MB).' }
        }

        // Validate MIME type
        const ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp']
        if (!ALLOWED_TYPES.includes(evidenceFile.type)) {
            return { error: 'Formato de foto no permitido (usar JPG, PNG o WebP).' }
        }

        try {
            const ext = evidenceFile.name.split('.').pop()?.toLowerCase() || 'jpg'
            const filename = `${crypto.randomUUID()}.${ext}`
            const storagePath = `${reportId}/${filename}`

            const { error: uploadError } = await supabase.storage
                .from(tenant.bucketEvidence)
                .upload(storagePath, evidenceFile, { upsert: false })

            if (uploadError) {
                console.error('[createReport] Upload error:', uploadError)
                // Don't block — report was created, just no evidence
            } else {
                // Get public URL
                const { data: urlData } = supabase.storage
                    .from(tenant.bucketEvidence)
                    .getPublicUrl(storagePath)

                const publicUrl = urlData?.publicUrl || null

                if (publicUrl) {
                    await supabase
                        .from(TABLES.reports)
                        .update({ evidence_urls: [publicUrl] })
                        .eq('id', reportId)
                }
            }
        } catch (e) {
            console.error('[createReport] Upload exception:', e)
        }
    }

    revalidatePath('/')
    revalidatePath('/admin/reportes')
    redirect(`/voucher?code=${encodeURIComponent(finalCode)}&t=${encodeURIComponent(finalToken)}`)
}

/**
 * Admin: change status of a buin_report and record the update.
 */
export async function adminUpdateReportStatus(
    reportId: string,
    newStatus: 'published' | 'routed' | 'in_progress' | 'resolved' | 'rejected' | 'pending',
    note?: string,
    area?: string,
    evidenceFile?: File | null
) {
    const supabase = await createClient()

    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Unauthorized' }

    // Check admin role
    const { data: profile } = await supabase
        .from(TABLES.profiles)
        .select('role')
        .eq('id', user.id)
        .single()

    if (!profile || !['admin', 'editor', 'verifier'].includes(profile.role)) {
        return { error: 'No tienes permisos para realizar esta acción.' }
    }

    // Fetch current report
    const { data: report } = await supabase
        .from(TABLES.reports)
        .select('status, evidence_urls, code')
        .eq('id', reportId)
        .single()

    if (!report) return { error: 'Reporte no encontrado' }
    const fromStatus = report.status

    // If resolving, we might want to upload evidence
    let finalEvidenceUrls = [...(report.evidence_urls as string[] || [])]
    if (newStatus === 'resolved' && evidenceFile && evidenceFile.size > 0) {
        try {
            const ext = evidenceFile.name.split('.').pop()?.toLowerCase() || 'jpg'
            const filename = `resolved_${crypto.randomUUID()}.${ext}`
            const storagePath = `${reportId}/${filename}`

            const { error: uploadError } = await supabase.storage
                .from(tenant.bucketEvidence)
                .upload(storagePath, evidenceFile)

            if (!uploadError) {
                const { data: urlData } = supabase.storage
                    .from(tenant.bucketEvidence)
                    .getPublicUrl(storagePath)
                if (urlData?.publicUrl) {
                    finalEvidenceUrls.push(urlData.publicUrl)
                }
            }
        } catch (e) {
            console.error('[adminUpdateReportStatus] Final evidence upload error:', e)
        }
    }

    // Update report
    const updatePayload: any = { status: newStatus, updated_at: new Date().toISOString() }
    if (newStatus === 'resolved') {
        updatePayload.evidence_urls = finalEvidenceUrls
    }

    const { error: updateError } = await supabase
        .from(TABLES.reports)
        .update(updatePayload)
        .eq('id', reportId)

    if (updateError) {
        return { error: `Error actualizando estado: ${updateError.message}` }
    }

    // Create a descriptive note if area is provided
    let finalNote = note?.trim() || ''
    if (newStatus === 'routed' && area) {
        finalNote = `Derivado a: ${area}${finalNote ? `. ${finalNote}` : ''}`
    }

    // Log the change
    await supabase.from(TABLES.report_updates).insert({
        report_id: reportId,
        from_status: fromStatus,
        to_status: newStatus,
        note: finalNote || null,
        created_by: user.id,
    })

    revalidatePath('/admin/reportes')
    revalidatePath(`/r/${report.code}`)
    revalidatePath('/')

    return { success: true }
}
